version: 0.2

phases:
  install:
    commands:
      - echo Installing source...
  build:
    commands:
      - echo Nothing to build for static HTML.

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*
  discard-paths: no
